title: title    #博客名
subtitle: subtitle  #博客副标题
description:          #网站描述, 用于爬虫抓取的关键词
author: author    #作者名称
email: email  #作者邮箱
language: zh-CN       #网页编码,中文
root: /			# 一定要从/开始，否则与github.io不能同步路径
deploy:
  type: github    #部署类型Github
  repository: git@github.com:YuYanzy/YuYanzy.github.io.git
  branch: master   #部署分支,一般使用master主分支