version: "2"
services:
    hexo:
        image: node:14.9
        container_name: hexo
        working_dir: /app
        volumes:
            - .:/app 
        ports: 
            - 30001:4000
        command: [sh, -c, "sleep infinity"]
        